version: '3.8'

networks:
  app-network:
    external: true
    name: shared-network

volumes:
  vault-data:

services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS}
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
    env_file:
      - ./.env
    networks:
      - app-network

  nginx-vault:
    image: nginx:latest
    container_name: nginx-vault
    ports:
      - "8200:8200"
    volumes:
      - ./nginx-vault.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vault
    networks:
      - app-network
